theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "/: {available} ({percentage})"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}/{mem_total} ({mem_used_percents})"
format_swap = "{swap_used}/{swap_total} (swap)"

[[block]]
block = "cpu"

[[block]]
block = "load"
interval = 5

[[block]]
block = "sound"

[[block]]
block = "keyboard_layout"

[[block]]
block = "net"
format = "{speed_down} down / {speed_up}"
device = "wlan0"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
